"""
Project paths and global configuration for the Shortage Prediction pipeline.

This module is the single source of truth for paths and panel parameters.
Every other script imports from here.
"""

from __future__ import annotations
from pathlib import Path

# ---- Anchored paths ----------------------------------------------------------

# Project root (parent of this script's grandparent)
ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "Data"

# Source datasets
UUTAH_FILE   = DATA / "24 - UUtah - Drug Shortage" / "raw" / "efox shortages small file through 2025 final.xlsx"
RECALL_FILT  = DATA / "22 - FDA - Recall" / "processed" / "recall_filtered.csv"
RECALL_FEAT  = DATA / "22 - FDA - Recall" / "processed" / "recall_fei_features.csv"
# Use the Valisure-filtered 14-drug FAERS dataset as the canonical FAERS input
# (generated by Data/15 - FDA - Adverse Event/processed/code/2026-05-12-faers_valisure_filter_and_eda.py)
FAERS_ALL    = DATA / "15 - FDA - Adverse Event" / "processed" / "faers_valisure_14_drugs_2026-05-12.csv"
FAERS_METF   = DATA / "15 - FDA - Adverse Event" / "processed" / "faers_metformin_anda_linked_2015Q1_2025Q3.csv"
VALISURE_CSV = DATA / "08 - Valisure" / "processed" / "valisure_all_drugs_combined.csv"
# Raw Valisure files (kept for reference). These are harder to use directly;
# prefer `VALISURE_CSV` (processed/merged) for pipeline inputs.
VALISURE_DOD = DATA / "08 - Valisure" / "raw" / "Discrete Scoring_DoD First 13 Drug Scores with ANDAs & NDCs.xlsx"  # raw reference — not used by default
VALISURE_FEI = DATA / "08 - Valisure" / "raw" / "FEIs_March 2026.xlsx"  # raw reference — use `VALISURE_CSV` instead
# Note: `valisure_all_drugs_combined.csv` is the most recent merged Valisure file
# (scores/FEI mappings are measured in 2024). We keep the combined file as the
# Valisure source but use the FAERS 14-drug filtered table as the FAERS input
# so the panel is not limited to Valisure's single-year measurement.
# REDICA processed outputs (preferred). These are the merged/processed files
# to use in the pipeline; avoid raw exports unless necessary for debugging.
REDICA_CSV   = DATA / "07 - Redica" / "processed" / "redica_all_drugs_combined.csv"
REDICA_AGG   = DATA / "07 - Redica" / "processed" / "SITE_RED_FLAG_AGG_SCORE.xlsx"
REDICA_EVENTS = DATA / "07 - Redica" / "processed" / "SITE_RED_FLAG_EVENTS.xlsx"

# 483 Text Analysis outputs (LLM-extracted FEI-level signals)
TEXT_FEATURES_CSV = DATA / "99 - Outputs - Text Analysis" / "483_fei_context_features.csv"
# Time-aware version: one row per (FEI, snapshot_date) — use this for shortage prediction
TEXT_TIMESERIES_CSV = DATA / "99 - Outputs - Text Analysis" / "483_fei_text_features_timeseries.csv"
# Combined timeseries (PDF + Redica): 99 FEIs; generated by 02_aggregate_fei_features.py --source combined
TEXT_TIMESERIES_COMBINED_CSV = DATA / "99 - Outputs - Text Analysis" / "483_fei_text_features_timeseries_combined.csv"
# Redica-only timeseries: 98 FEIs, current LLM pipeline only — USE THIS FOR MODELING
# Generated by: python 02_aggregate_fei_features.py --source redica
TEXT_TIMESERIES_REDICA_CSV   = DATA / "99 - Outputs - Text Analysis" / "483_fei_text_features_timeseries_redica.csv"
# Combined observation universe (PDF + Redica, 1737 obs, 99 FEIs)
COMBINED_OBS_CSV = DATA / "99 - Outputs - Text Analysis" / "483_combined_obs_universe.csv"

# ── TODO: SDUD volume weighting ───────────────────────────────────────────────
# SDUD volume shares (FEI × drug × year) are NOT yet incorporated into the
# shortage/recall models. The NDC→FEI bridge (NDC_FEI_MAP_CSV) currently stores
# only the 5-4 labeler-product NDC, missing the 2-digit package code needed to
# join to SDUD's 11-digit ndc11 column.  To fix:
#   1. Extend the bridge via FDA NDC package.csv: PRODUCTNDC (5-4) → NDCPACKAGECODE (11-digit)
#   2. Join SDUD on ndc11_zeropadded == NDCPACKAGECODE_stripped
#   3. Aggregate to FEI × drug × year and pass into utils.load_sdud_fei_volume()
#   4. Add sdud_volume_share as a feature or sample weight in m14 / shortage model
# ─────────────────────────────────────────────────────────────────────────────
# FEI→drug_norm bridge: sheet "API Only_FEI Mapping" in VALISURE_FEI (defined above)

# SDUD and NDC→FEI bridge (used by utils.load_sdud_fei_volume)
SDUD_MONTHLY_CSV = DATA / "04 - Medicaid - SDUD" / "processed" / "2025-12-18-SDUDmonthly.csv"
NDC_FEI_MAP_CSV  = DATA / "17 - NDC, FEI Mapping" / "ndc_fei_from_labels.csv"

# Output paths
OUT_ROOT  = DATA / "99 - Outputs - Shortage Prediction"
OUT_DATA  = OUT_ROOT / "data"
OUT_FIGS  = OUT_ROOT / "outputs" / "figures"
OUT_TABS  = OUT_ROOT / "outputs" / "tables"
OUT_MODELS = OUT_ROOT / "outputs" / "models"
OUT_LOGS  = OUT_ROOT / "logs"

for p in [OUT_DATA, OUT_FIGS, OUT_TABS, OUT_MODELS, OUT_LOGS]:
    p.mkdir(parents=True, exist_ok=True)

# ---- Panel parameters --------------------------------------------------------

# Panel year window: set to 2015–2024 by default.
# - `PANEL_START_YEAR=2015` because FAERS ASCII downloads in this project begin in 2015.
#   The pipeline can be run further back if you add older raw FAERS quarters.
PANEL_START_YEAR = 2015
# - `PANEL_END_YEAR=2024` is used because it's the last full year where cross-
#   source coverage is available (Valisure combined scores/reporting is from 2024
#   and many other sources are complete through 2024). You can extend this
#   endpoint if newer yearly data become available.
PANEL_END_YEAR   = 2024   # last full year with all sources

# Lag specification: features at year t predict shortage in year t+1
PREDICTION_LAG_YEARS = 1
ROLLING_WINDOW_YEARS = 3  # use 3-year rolling sums for rare-event features

# Random seed
SEED = 7
